language: python
python: 2.7
dist: trusty

after_success:
  - echo "<---------------Build success--------------->\n"
  - ls -l BUILD\UBLOX_C030_N211\GCC_ARM

after_failure:
  - echo "Build failure"

before_install:
  # Make sure pipefail
  - set -o pipefail
  # Setup apt to cache
  - mkdir -p $HOME/.cache/apt/partial
  - sudo rm -rf /var/cache/apt/archives
  - sudo ln -s $HOME/.cache/apt /var/cache/apt/archives
  # Setup ppa to make sure arm-none-eabi-gcc is correct version
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo add-apt-repository -y ppa:deadsnakes/ppa
  # workaround for https://travis-ci.community/t/then-sudo-apt-get-update-failed-public-key-is-not-available-no-pubkey-6b05f25d762e3157-in-ubuntu-xenial/1728
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 762E3157
  - travis_retry $(! sudo apt-get update 2>&1 |grep Failed)

install:
  - sudo apt-get install gcc-arm-embedded
  - arm-none-eabi-gcc --version
  - pip install mbed-cli
  - mbed new .
  - mbed update


script:
  # Check that example compiles with littlefs + spif
  - mbed compile -t GCC_ARM -m UBLOX_C030_N211 --source=./bootloader -c
  - mbed compile -t GCC_ARM -m UBLOX_C030_N211